[package]
name = "bern-kernel"
version = "0.0.1"
authors = ["Stefan Lüthi <stefan.luethi@outlook.com>"]
edition = "2018"

[dependencies]
bern-arch = { version = "*", path = "../bern_arch" }
arr_macro = "0.1.3"