[package]
name = "bern-kernel"
version = "0.0.1"
authors = ["Stefan Lüthi <stefan.luethi@outlook.com>"]
edition = "2018"

[dependencies]
cortex-m-rt = "0.6.10"
cortex-m = { version = "0.7.2", features = ["inline-asm"] }
